CREATE TABLE
    IF NOT EXISTS "__EFMigrationsHistory" (
        "MigrationId" character varying(150) NOT NULL,
        "ProductVersion" character varying(32) NOT NULL,
        CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
    );

START TRANSACTION;

CREATE TABLE
    "AspNetRoles" (
        "Id" text NOT NULL,
        "Name" character varying(256) NULL,
        "NormalizedName" character varying(256) NULL,
        "ConcurrencyStamp" text NULL,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );

CREATE TABLE
    "AspNetUsers" (
        "Id" text NOT NULL,
        "InGame" boolean NOT NULL,
        "UserName" character varying(256) NULL,
        "NormalizedUserName" character varying(256) NULL,
        "Email" character varying(256) NULL,
        "NormalizedEmail" character varying(256) NULL,
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text NULL,
        "SecurityStamp" text NULL,
        "ConcurrencyStamp" text NULL,
        "PhoneNumber" text NULL,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp
        with
            time zone NULL,
            "LockoutEnabled" boolean NOT NULL,
            "AccessFailedCount" integer NOT NULL,
            CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    );

CREATE TABLE
    "Tbl_BvacMaster" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "MerId" text NULL,
        "EncryptKey" text NULL,
        "ReturnKey" text NULL,
        "DepositGetTokentUrl" text NULL,
        "DepositRequestUrl" text NULL,
        "DepositSubmitUrl" text NULL,
        "DepositNotifyUrl" text NULL,
        "CreatedAt" timestamp
        with
            time zone NOT NULL,
            "UpdatedAt" timestamp
        with
            time zone NOT NULL,
            CONSTRAINT "PK_Tbl_BvacMaster" PRIMARY KEY ("Id")
    );

CREATE TABLE
    "Tbl_Currency" (
        "Id" integer NOT NULL,
        "Name" text NULL,
        "CreatedAt" timestamp
        with
            time zone NOT NULL,
            "UpdatedAt" timestamp
        with
            time zone NOT NULL,
            CONSTRAINT "PK_Tbl_Currency" PRIMARY KEY ("Id")
    );

CREATE TABLE
    "Tbl_Egm" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Ip" text NULL,
        "Model" text NULL,
        "Brand" text NULL,
        "DisplayName" text NULL,
        "StreamUrl" text NULL,
        "ConnectStatus" integer NOT NULL,
        "InGame" boolean NOT NULL,
        "CreatedAt" timestamp
        with
            time zone NOT NULL,
            "UpdatedAt" timestamp
        with
            time zone NOT NULL,
            CONSTRAINT "PK_Tbl_Egm" PRIMARY KEY ("Id")
    );

CREATE TABLE
    "Tbl_PaymentMethod" (
        "Id" integer NOT NULL,
        "Name" text NULL,
        "Description" text NULL,
        "IsEnable" boolean NOT NULL,
        "CreatedAt" timestamp
        with
            time zone NOT NULL,
            "UpdatedAt" timestamp
        with
            time zone NOT NULL,
            CONSTRAINT "PK_Tbl_PaymentMethod" PRIMARY KEY ("Id")
    );

CREATE TABLE
    "Tbl_Photo" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FileSize" integer NULL,
        "Data" bytea NULL,
        "CreatedAt" timestamp
        with
            time zone NOT NULL,
            "UpdatedAt" timestamp
        with
            time zone NOT NULL,
            CONSTRAINT "PK_Tbl_Photo" PRIMARY KEY ("Id")
    );

CREATE TABLE
    "AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" text NOT NULL,
        "ClaimType" text NULL,
        "ClaimValue" text NULL,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
    );

CREATE TABLE
    "AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NOT NULL,
        "ClaimType" text NULL,
        "ClaimValue" text NULL,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );

CREATE TABLE
    "AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text NULL,
        "UserId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );

CREATE TABLE
    "AspNetUserRoles" (
        "UserId" text NOT NULL,
        "RoleId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );

CREATE TABLE
    "AspNetUserTokens" (
        "UserId" text NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text NULL,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );

CREATE TABLE
    "Tbl_AppUserRefreshToken" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "AppUserId" text NULL,
        "RefreshToken" text NULL,
        "RefreshTokenExpiryTime" timestamp
        with
            time zone NOT NULL,
            "CreatedAt" timestamp
        with
            time zone NOT NULL,
            "UpdatedAt" timestamp
        with
            time zone NOT NULL,
            CONSTRAINT "PK_Tbl_AppUserRefreshToken" PRIMARY KEY ("Id"),
            CONSTRAINT "FK_Tbl_AppUserRefreshToken_AspNetUsers_AppUserId" FOREIGN KEY ("AppUserId") REFERENCES "AspNetUsers" ("Id")
    );

CREATE TABLE
    "Tbl_InternalUser" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "AppUserId" text NULL,
        "CreatedAt" timestamp
        with
            time zone NOT NULL,
            "UpdatedAt" timestamp
        with
            time zone NOT NULL,
            CONSTRAINT "PK_Tbl_InternalUser" PRIMARY KEY ("Id"),
            CONSTRAINT "FK_Tbl_InternalUser_AspNetUsers_AppUserId" FOREIGN KEY ("AppUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );

CREATE TABLE
    "Tbl_OnlineUser" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "AppUserId" text NULL,
        "AreaCode" integer NOT NULL,
        "MyInvitationCode" character(8) NULL,
        "Level" integer NOT NULL,
        "IsBlock" boolean NOT NULL,
        "Remark" text NULL,
        "CreatedAt" timestamp
        with
            time zone NOT NULL,
            "UpdatedAt" timestamp
        with
            time zone NOT NULL,
            CONSTRAINT "PK_Tbl_OnlineUser" PRIMARY KEY ("Id"),
            CONSTRAINT "FK_Tbl_OnlineUser_AspNetUsers_AppUserId" FOREIGN KEY ("AppUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );

CREATE TABLE
    "Tbl_OnlineWallet" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "AppUserId" text NULL,
        "IsEnabled" boolean NOT NULL,
        "DepositWithdrawBalance" numeric(12, 2) NOT NULL DEFAULT 0.0,
        "GamePointBalance" numeric(12, 2) NOT NULL DEFAULT 0.0,
        "PromotionsBalance" numeric(12, 2) NOT NULL DEFAULT 0.0,
        "CreatedAt" timestamp
        with
            time zone NOT NULL,
            "UpdatedAt" timestamp
        with
            time zone NOT NULL,
            CONSTRAINT "PK_Tbl_OnlineWallet" PRIMARY KEY ("Id"),
            CONSTRAINT "CK_Tbl_OnlineWallet_DepositWithdrawBalance_SlotPointBalance_Su~" CHECK (
                "DepositWithdrawBalance" + "GamePointBalance" >= 0
            ),
            CONSTRAINT "CK_Tbl_OnlineWallet_PromotionsBalance_GreaterThanNegative0" CHECK ("PromotionsBalance" >= 0),
            CONSTRAINT "FK_Tbl_OnlineWallet_AspNetUsers_AppUserId" FOREIGN KEY ("AppUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );

COMMENT ON COLUMN "Tbl_OnlineWallet"."DepositWithdrawBalance" IS '儲值提領點數，即儲值和提領的差額';

COMMENT ON COLUMN "Tbl_OnlineWallet"."GamePointBalance" IS '遊戲機輸贏點數';

COMMENT ON COLUMN "Tbl_OnlineWallet"."PromotionsBalance" IS '贈送點數';

CREATE TABLE
    "Tbl_SmsVerify" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Code" text NOT NULL,
        "AppUserId" text NOT NULL,
        "CreatedAt" timestamp
        with
            time zone NOT NULL,
            "UpdatedAt" timestamp
        with
            time zone NOT NULL,
            CONSTRAINT "PK_Tbl_SmsVerify" PRIMARY KEY ("Id"),
            CONSTRAINT "FK_Tbl_SmsVerify_AspNetUsers_AppUserId" FOREIGN KEY ("AppUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );

CREATE TABLE
    "Tbl_UserLoginRecord" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "AppUserId" text NOT NULL,
        "CreatedAt" timestamp
        with
            time zone NOT NULL,
            "UpdatedAt" timestamp
        with
            time zone NOT NULL,
            CONSTRAINT "PK_Tbl_UserLoginRecord" PRIMARY KEY ("Id"),
            CONSTRAINT "FK_Tbl_UserLoginRecord_AspNetUsers_AppUserId" FOREIGN KEY ("AppUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );

CREATE TABLE
    "Tbl_CurrencyRate" (
        "Rate" numeric NOT NULL,
        "CurrencyId" integer NOT NULL,
        "IsEnable" boolean NOT NULL,
        "CreatedAt" timestamp
        with
            time zone NOT NULL,
            "UpdatedAt" timestamp
        with
            time zone NOT NULL,
            CONSTRAINT "PK_Tbl_CurrencyRate" PRIMARY KEY ("CurrencyId", "Rate"),
            CONSTRAINT "FK_Tbl_CurrencyRate_Tbl_Currency_CurrencyId" FOREIGN KEY ("CurrencyId") REFERENCES "Tbl_Currency" ("Id") ON DELETE CASCADE
    );

CREATE TABLE
    "Tbl_AftTransaction" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "EgmId" integer NOT NULL,
        "AppUserId" text NULL,
        "EgmCurrentCredit" integer NOT NULL,
        "CreditAmount" integer NOT NULL,
        "PointAmount" numeric NOT NULL,
        "Denomination" numeric NOT NULL,
        "IsOnline" boolean NOT NULL,
        "AftType" integer NOT NULL,
        "CreatedAt" timestamp
        with
            time zone NOT NULL,
            "UpdatedAt" timestamp
        with
            time zone NOT NULL,
            CONSTRAINT "PK_Tbl_AftTransaction" PRIMARY KEY ("Id"),
            CONSTRAINT "FK_Tbl_AftTransaction_AspNetUsers_AppUserId" FOREIGN KEY ("AppUserId") REFERENCES "AspNetUsers" ("Id"),
            CONSTRAINT "FK_Tbl_AftTransaction_Tbl_Egm_EgmId" FOREIGN KEY ("EgmId") REFERENCES "Tbl_Egm" ("Id") ON DELETE CASCADE
    );

CREATE TABLE
    "Tbl_EgmAppUser" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "EgmId" integer NOT NULL,
        "AppUserId" text NULL,
        "Status" integer NOT NULL,
        "IsOnline" boolean NOT NULL,
        "CreatedAt" timestamp
        with
            time zone NOT NULL,
            "UpdatedAt" timestamp
        with
            time zone NOT NULL,
            CONSTRAINT "PK_Tbl_EgmAppUser" PRIMARY KEY ("Id"),
            CONSTRAINT "FK_Tbl_EgmAppUser_AspNetUsers_AppUserId" FOREIGN KEY ("AppUserId") REFERENCES "AspNetUsers" ("Id"),
            CONSTRAINT "FK_Tbl_EgmAppUser_Tbl_Egm_EgmId" FOREIGN KEY ("EgmId") REFERENCES "Tbl_Egm" ("Id") ON DELETE SET NULL
    );

CREATE TABLE
    "Tbl_EgmDisconnectionLog" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "EgmId" integer NOT NULL,
        "Reason" integer NOT NULL,
        "Description" text NULL,
        "CreatedAt" timestamp
        with
            time zone NOT NULL,
            "UpdatedAt" timestamp
        with
            time zone NOT NULL,
            CONSTRAINT "PK_Tbl_EgmDisconnectionLog" PRIMARY KEY ("Id"),
            CONSTRAINT "FK_Tbl_EgmDisconnectionLog_Tbl_Egm_EgmId" FOREIGN KEY ("EgmId") REFERENCES "Tbl_Egm" ("Id") ON DELETE CASCADE
    );

CREATE TABLE
    "Tbl_PaymentMethodCurrency" (
        "PaymentMethodId" integer NOT NULL,
        "CurrencyId" integer NOT NULL,
        "CreatedAt" timestamp
        with
            time zone NOT NULL,
            "UpdatedAt" timestamp
        with
            time zone NOT NULL,
            CONSTRAINT "PK_Tbl_PaymentMethodCurrency" PRIMARY KEY ("PaymentMethodId", "CurrencyId"),
            CONSTRAINT "FK_Tbl_PaymentMethodCurrency_Tbl_Currency_CurrencyId" FOREIGN KEY ("CurrencyId") REFERENCES "Tbl_Currency" ("Id") ON DELETE CASCADE,
            CONSTRAINT "FK_Tbl_PaymentMethodCurrency_Tbl_PaymentMethod_PaymentMethodId" FOREIGN KEY ("PaymentMethodId") REFERENCES "Tbl_PaymentMethod" ("Id") ON DELETE CASCADE
    );

CREATE TABLE
    "Tbl_Customer" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "AppUserId" text NULL,
        "Gender" integer NOT NULL,
        "ActualName" text NULL,
        "IdentityType" integer NOT NULL,
        "IdentityNumber" text NULL,
        "Address" text NULL,
        "Birthday" date NOT NULL,
        "MyInvitationCode" character(8) NULL,
        "Level" integer NOT NULL,
        "PhotoId" integer NULL,
        "IsBlock" boolean NOT NULL,
        "Remark" text NULL,
        "CreatedAt" timestamp
        with
            time zone NOT NULL,
            "UpdatedAt" timestamp
        with
            time zone NOT NULL,
            CONSTRAINT "PK_Tbl_Customer" PRIMARY KEY ("Id"),
            CONSTRAINT "FK_Tbl_Customer_AspNetUsers_AppUserId" FOREIGN KEY ("AppUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
            CONSTRAINT "FK_Tbl_Customer_Tbl_Photo_PhotoId" FOREIGN KEY ("PhotoId") REFERENCES "Tbl_Photo" ("Id")
    );

CREATE TABLE
    "Tbl_OnlineUserInvitation" (
        "InviterId" integer NOT NULL,
        "InviteeId" integer NOT NULL,
        "IsValid" boolean NOT NULL DEFAULT FALSE,
        "CreatedAt" timestamp
        with
            time zone NOT NULL,
            "UpdatedAt" timestamp
        with
            time zone NOT NULL,
            CONSTRAINT "PK_Tbl_OnlineUserInvitation" PRIMARY KEY ("InviterId", "InviteeId"),
            CONSTRAINT "CK_Tbl_OnlineUserInvitation_InviterId_InviteeId_not_same" CHECK ("InviteeId" <> "InviterId"),
            CONSTRAINT "FK_Tbl_OnlineUserInvitation_Tbl_OnlineUser_InviteeId" FOREIGN KEY ("InviteeId") REFERENCES "Tbl_OnlineUser" ("Id") ON DELETE CASCADE,
            CONSTRAINT "FK_Tbl_OnlineUserInvitation_Tbl_OnlineUser_InviterId" FOREIGN KEY ("InviterId") REFERENCES "Tbl_OnlineUser" ("Id") ON DELETE CASCADE
    );

CREATE TABLE
    "Tbl_OnlineUserTransaction" (
        "Id" uuid NOT NULL,
        "OnlineWalletId" integer NOT NULL,
        "CurrencyId" integer NOT NULL,
        "CurrencyAmount" numeric(12, 2) NOT NULL,
        "CurrencyRate" numeric(12, 2) NOT NULL,
        "PointAmount" numeric(12, 2) NOT NULL,
        "PaymentMethodId" integer NOT NULL,
        "TransactionType" integer NOT NULL,
        "TransactionStatus" integer NOT NULL,
        "Comment" text NULL,
        "CreatedAt" timestamp
        with
            time zone NOT NULL,
            "UpdatedAt" timestamp
        with
            time zone NOT NULL,
            CONSTRAINT "PK_Tbl_OnlineUserTransaction" PRIMARY KEY ("Id"),
            CONSTRAINT "CK_OnlineUserTransaction_PointAmount_Type1" CHECK (
                (
                    "TransactionType" = 1
                    AND "PointAmount" >= 0
                )
                OR "TransactionType" <> 1
            ),
            CONSTRAINT "CK_OnlineUserTransaction_PointAmount_Type2" CHECK (
                (
                    "TransactionType" = 2
                    AND "PointAmount" <= 0
                )
                OR "TransactionType" <> 2
            ),
            CONSTRAINT "FK_Tbl_OnlineUserTransaction_Tbl_Currency_CurrencyId" FOREIGN KEY ("CurrencyId") REFERENCES "Tbl_Currency" ("Id") ON DELETE CASCADE,
            CONSTRAINT "FK_Tbl_OnlineUserTransaction_Tbl_OnlineWallet_OnlineWalletId" FOREIGN KEY ("OnlineWalletId") REFERENCES "Tbl_OnlineWallet" ("Id") ON DELETE CASCADE,
            CONSTRAINT "FK_Tbl_OnlineUserTransaction_Tbl_PaymentMethod_PaymentMethodId" FOREIGN KEY ("PaymentMethodId") REFERENCES "Tbl_PaymentMethod" ("Id") ON DELETE CASCADE
    );

CREATE TABLE
    "Tbl_EgmTransaction" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "EgmAppUserId" integer NOT NULL,
        "AppUserId" text NULL,
        "EgmId" integer NOT NULL,
        "Denomination" numeric NOT NULL,
        "EgmCoinIn" bigint NOT NULL,
        "EgmCoinOut" bigint NOT NULL,
        "CreditBalance" integer NOT NULL,
        "EgmCurrentCredit" bigint NOT NULL,
        "BetCreditAmount" integer NOT NULL,
        "CurrencyBalance" numeric NOT NULL,
        "IsOnline" boolean NOT NULL,
        "CreatedAt" timestamp
        with
            time zone NOT NULL,
            "UpdatedAt" timestamp
        with
            time zone NOT NULL,
            CONSTRAINT "PK_Tbl_EgmTransaction" PRIMARY KEY ("Id"),
            CONSTRAINT "FK_Tbl_EgmTransaction_AspNetUsers_AppUserId" FOREIGN KEY ("AppUserId") REFERENCES "AspNetUsers" ("Id"),
            CONSTRAINT "FK_Tbl_EgmTransaction_Tbl_EgmAppUser_EgmAppUserId" FOREIGN KEY ("EgmAppUserId") REFERENCES "Tbl_EgmAppUser" ("Id") ON DELETE CASCADE,
            CONSTRAINT "FK_Tbl_EgmTransaction_Tbl_Egm_EgmId" FOREIGN KEY ("EgmId") REFERENCES "Tbl_Egm" ("Id") ON DELETE CASCADE
    );

CREATE TABLE
    "Tbl_Invitation" (
        "InviterId" integer NOT NULL,
        "InviteeId" integer NOT NULL,
        "IsValid" boolean NOT NULL DEFAULT FALSE,
        "CreatedAt" timestamp
        with
            time zone NOT NULL,
            "UpdatedAt" timestamp
        with
            time zone NOT NULL,
            CONSTRAINT "PK_Tbl_Invitation" PRIMARY KEY ("InviterId", "InviteeId"),
            CONSTRAINT "CK_Tbl_Invitation_InviterId_InviteeId_not_same" CHECK ("InviteeId" <> "InviterId"),
            CONSTRAINT "FK_Tbl_Invitation_Tbl_Customer_InviteeId" FOREIGN KEY ("InviteeId") REFERENCES "Tbl_Customer" ("Id") ON DELETE CASCADE,
            CONSTRAINT "FK_Tbl_Invitation_Tbl_Customer_InviterId" FOREIGN KEY ("InviterId") REFERENCES "Tbl_Customer" ("Id") ON DELETE CASCADE
    );

CREATE TABLE
    "Tbl_BvacNotify" (
        "OnlineUserTransactionId" uuid NOT NULL,
        "BvacBillId" text NULL,
        "Amount" numeric NOT NULL,
        "CompleteDate" text NULL,
        "Remark" text NULL,
        "ReturnChecksum" text NULL,
        "OrderId" text NULL,
        "OrderKey" text NULL,
        "ReturnMsg" text NULL,
        "Value" text NULL,
        "RequestedAmt" numeric NOT NULL,
        "SysDate" text NULL,
        "BackAccount" text NULL,
        "BackName" text NULL,
        "Token" text NULL,
        "CreatedAt" timestamp
        with
            time zone NOT NULL,
            "UpdatedAt" timestamp
        with
            time zone NOT NULL,
            CONSTRAINT "PK_Tbl_BvacNotify" PRIMARY KEY ("OnlineUserTransactionId"),
            CONSTRAINT "FK_Tbl_BvacNotify_Tbl_OnlineUserTransaction_OnlineUserTransact~" FOREIGN KEY ("OnlineUserTransactionId") REFERENCES "Tbl_OnlineUserTransaction" ("Id") ON DELETE CASCADE
    );

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "IX_AspNetUsers_Email" ON "AspNetUsers" ("Email");

CREATE UNIQUE INDEX "IX_AspNetUsers_PhoneNumber" ON "AspNetUsers" ("PhoneNumber");

CREATE UNIQUE INDEX "IX_AspNetUsers_UserName" ON "AspNetUsers" ("UserName");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE INDEX "IX_Tbl_AftTransaction_AppUserId" ON "Tbl_AftTransaction" ("AppUserId");

CREATE INDEX "IX_Tbl_AftTransaction_EgmId" ON "Tbl_AftTransaction" ("EgmId");

CREATE UNIQUE INDEX "IX_Tbl_AppUserRefreshToken_AppUserId" ON "Tbl_AppUserRefreshToken" ("AppUserId");

CREATE UNIQUE INDEX "IX_Tbl_AppUserRefreshToken_RefreshToken" ON "Tbl_AppUserRefreshToken" ("RefreshToken");

CREATE UNIQUE INDEX "IX_Tbl_CurrencyRate_EnabledCurrency_CurrencyId" ON "Tbl_CurrencyRate" ("CurrencyId")
WHERE
    "IsEnable" = true;

CREATE UNIQUE INDEX "IX_Tbl_Customer_AppUserId" ON "Tbl_Customer" ("AppUserId");

CREATE UNIQUE INDEX "IX_Tbl_Customer_IdentityNumber" ON "Tbl_Customer" ("IdentityNumber");

CREATE UNIQUE INDEX "IX_Tbl_Customer_MyInvitationCode" ON "Tbl_Customer" ("MyInvitationCode");

CREATE INDEX "IX_Tbl_Customer_PhotoId" ON "Tbl_Customer" ("PhotoId");

CREATE UNIQUE INDEX "IX_Tbl_Egm_Ip" ON "Tbl_Egm" ("Ip");

CREATE UNIQUE INDEX "IX_Tbl_Egm_StreamUrl" ON "Tbl_Egm" ("StreamUrl");

CREATE UNIQUE INDEX "IX_EgmAppUser_AppUserId_Status" ON "Tbl_EgmAppUser" ("AppUserId")
WHERE
    "Status" = 1;

CREATE UNIQUE INDEX "IX_EgmAppUser_EgmId_Status" ON "Tbl_EgmAppUser" ("EgmId")
WHERE
    "Status" = 1;

CREATE INDEX "IX_Tbl_EgmDisconnectionLog_EgmId" ON "Tbl_EgmDisconnectionLog" ("EgmId");

CREATE INDEX "IX_Tbl_EgmTransaction_AppUserId" ON "Tbl_EgmTransaction" ("AppUserId");

CREATE INDEX "IX_Tbl_EgmTransaction_EgmAppUserId" ON "Tbl_EgmTransaction" ("EgmAppUserId");

CREATE INDEX "IX_Tbl_EgmTransaction_EgmId" ON "Tbl_EgmTransaction" ("EgmId");

CREATE UNIQUE INDEX "IX_Tbl_InternalUser_AppUserId" ON "Tbl_InternalUser" ("AppUserId");

CREATE UNIQUE INDEX "IX_Tbl_Invitation_InviteeId" ON "Tbl_Invitation" ("InviteeId");

CREATE UNIQUE INDEX "IX_Tbl_OnlineUser_AppUserId" ON "Tbl_OnlineUser" ("AppUserId");

CREATE UNIQUE INDEX "IX_Tbl_OnlineUser_MyInvitationCode" ON "Tbl_OnlineUser" ("MyInvitationCode");

CREATE UNIQUE INDEX "IX_Tbl_OnlineUserInvitation_InviteeId" ON "Tbl_OnlineUserInvitation" ("InviteeId");

CREATE INDEX "IX_Tbl_OnlineUserTransaction_CurrencyId" ON "Tbl_OnlineUserTransaction" ("CurrencyId");

CREATE INDEX "IX_Tbl_OnlineUserTransaction_OnlineWalletId" ON "Tbl_OnlineUserTransaction" ("OnlineWalletId");

CREATE INDEX "IX_Tbl_OnlineUserTransaction_PaymentMethodId" ON "Tbl_OnlineUserTransaction" ("PaymentMethodId");

CREATE UNIQUE INDEX "IX_Tbl_OnlineWallet_AppUserId" ON "Tbl_OnlineWallet" ("AppUserId");

CREATE INDEX "IX_Tbl_PaymentMethodCurrency_CurrencyId" ON "Tbl_PaymentMethodCurrency" ("CurrencyId");

CREATE UNIQUE INDEX "IX_Tbl_SmsVerify_AppUserId" ON "Tbl_SmsVerify" ("AppUserId");

CREATE UNIQUE INDEX "IX_Tbl_SmsVerify_Code" ON "Tbl_SmsVerify" ("Code");

CREATE INDEX "IX_Tbl_UserLoginRecord_AppUserId" ON "Tbl_UserLoginRecord" ("AppUserId");

INSERT INTO
    "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES
    ('20230704044236_Init', '7.0.5');

COMMIT;

START TRANSACTION;

CREATE TABLE
    "Tbl_SmsMaster" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserName" text NULL,
        "Password" text NULL,
        "IsEnable" boolean NOT NULL,
        "CreatedAt" timestamp
        with
            time zone NOT NULL,
            "UpdatedAt" timestamp
        with
            time zone NOT NULL,
            CONSTRAINT "PK_Tbl_SmsMaster" PRIMARY KEY ("Id")
    );

INSERT INTO
    "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES
    ('20230705060528_AddSmsMaster', '7.0.5');

COMMIT;

START TRANSACTION;

ALTER TABLE "Tbl_EgmTransaction"
RENAME COLUMN "CurrencyBalance" TO "RewardPointsRatio";

ALTER TABLE "Tbl_EgmTransaction"
RENAME COLUMN "CreditBalance" TO "WinCreditAmount";

ALTER TABLE "Tbl_EgmTransaction" ADD "RewardPoints" numeric NOT NULL DEFAULT 0.0;

ALTER TABLE "Tbl_EgmTransaction" ADD "Serial" text NULL;

CREATE TABLE
    "Tbl_UnselectedEgmTransaction" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CreatedAt" timestamp
        with
            time zone NOT NULL,
            "UpdatedAt" timestamp
        with
            time zone NOT NULL,
            "EgmId" integer NOT NULL,
            "Denomination" numeric NOT NULL,
            "EgmCoinIn" bigint NOT NULL,
            "EgmCoinOut" bigint NOT NULL,
            "EgmCurrentCredit" bigint NOT NULL,
            "BetCreditAmount" integer NOT NULL,
            "WinCreditAmount" integer NOT NULL,
            "Serial" text NULL,
            "IsOnline" boolean NOT NULL,
            CONSTRAINT "PK_Tbl_UnselectedEgmTransaction" PRIMARY KEY ("Id"),
            CONSTRAINT "FK_Tbl_UnselectedEgmTransaction_Tbl_Egm_EgmId" FOREIGN KEY ("EgmId") REFERENCES "Tbl_Egm" ("Id") ON DELETE CASCADE
    );

CREATE INDEX "IX_Tbl_UnselectedEgmTransaction_EgmId" ON "Tbl_UnselectedEgmTransaction" ("EgmId");

INSERT INTO
    "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES
    (
        '20230707091015_AddBaseEgmTransactionTable',
        '7.0.5'
    );

COMMIT;

START TRANSACTION;

ALTER TABLE "Tbl_BvacMaster"
RENAME COLUMN "DepositGetTokentUrl" TO "DepositGetTokenUrl";

INSERT INTO
    "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES
    ('20230707110522_TableColumnTypo', '7.0.5');

COMMIT;

START TRANSACTION;

ALTER TABLE "Tbl_AftTransaction"
RENAME COLUMN "EgmCurrentCredit" TO "EgmPromoCredit";

ALTER TABLE "Tbl_AftTransaction" ADD "EgmCashCredit" integer NOT NULL DEFAULT 0;

ALTER TABLE "Tbl_AftTransaction" ADD "IsPromo" boolean NOT NULL DEFAULT FALSE;

INSERT INTO
    "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES
    (
        '20230717063243_UpdateAftTransactionIsPromoCashCreditPromoCredit',
        '7.0.5'
    );

COMMIT;

START TRANSACTION;

ALTER TABLE "Tbl_UnselectedEgmTransaction"
RENAME COLUMN "EgmCurrentCredit" TO "EgmPromoCredit";

ALTER TABLE "Tbl_EgmTransaction"
RENAME COLUMN "EgmCurrentCredit" TO "EgmPromoCredit";

ALTER TABLE "Tbl_UnselectedEgmTransaction" ADD "EgmCashCredit" bigint NOT NULL DEFAULT 0;

ALTER TABLE "Tbl_EgmTransaction" ADD "EgmCashCredit" bigint NOT NULL DEFAULT 0;

INSERT INTO
    "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES
    (
        '20230717063850_UpdateEgmTransactionCashCreditPromoCredit',
        '7.0.5'
    );

COMMIT;

START TRANSACTION;

ALTER TABLE "Tbl_OnlineWallet"
RENAME COLUMN "PromotionsBalance" TO "PromPointBalance";

ALTER TABLE "Tbl_OnlineWallet" ADD "RewardPointBalance" numeric(12, 2) NOT NULL DEFAULT 0.0;

COMMENT ON COLUMN "Tbl_OnlineWallet"."RewardPointBalance" IS '回饋點數';

INSERT INTO
    "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES
    (
        '20230718061825_AddOnlineWalletRewardPointBalance',
        '7.0.5'
    );

COMMIT;

START TRANSACTION;

ALTER TABLE "Tbl_OnlineWallet"
ALTER COLUMN "RewardPointBalance" TYPE numeric(12, 3);

INSERT INTO
    "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES
    (
        '20230719090126_UpdateOnlineWalletRewardPoint',
        '7.0.5'
    );

COMMIT;

START TRANSACTION;

ALTER TABLE "Tbl_OnlineWallet"
ALTER COLUMN "RewardPointBalance" TYPE numeric(12, 2);

ALTER TABLE "Tbl_OnlineWallet" ADD "RewardPointDisplay" numeric(12, 3) NOT NULL DEFAULT 0.0;

COMMENT ON COLUMN "Tbl_OnlineWallet"."RewardPointDisplay" IS '回饋點數顯示在user介面';

INSERT INTO
    "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES
    (
        '20230719093207_OnlineWalletAddRewardPointDisplay',
        '7.0.5'
    );

COMMIT;

START TRANSACTION;

CREATE TABLE
    "Tbl_OnlineAftFail" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "IsReset" boolean NOT NULL,
        "ErrorMessage" text NULL,
        "CreatedAt" timestamp
        with
            time zone NOT NULL,
            "UpdatedAt" timestamp
        with
            time zone NOT NULL,
            "EgmId" integer NOT NULL,
            "AppUserId" text NULL,
            "EgmCashCredit" integer NOT NULL,
            "EgmPromoCredit" integer NOT NULL,
            "CreditAmount" integer NOT NULL,
            "PointAmount" numeric NOT NULL,
            "Denomination" numeric NOT NULL,
            "AftType" integer NOT NULL,
            CONSTRAINT "PK_Tbl_OnlineAftFail" PRIMARY KEY ("Id"),
            CONSTRAINT "FK_Tbl_OnlineAftFail_AspNetUsers_AppUserId" FOREIGN KEY ("AppUserId") REFERENCES "AspNetUsers" ("Id"),
            CONSTRAINT "FK_Tbl_OnlineAftFail_Tbl_Egm_EgmId" FOREIGN KEY ("EgmId") REFERENCES "Tbl_Egm" ("Id") ON DELETE CASCADE
    );

CREATE INDEX "IX_Tbl_OnlineAftFail_AppUserId" ON "Tbl_OnlineAftFail" ("AppUserId");

CREATE INDEX "IX_Tbl_OnlineAftFail_EgmId" ON "Tbl_OnlineAftFail" ("EgmId");

INSERT INTO
    "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES
    ('20230720090743_AddOnlineAftFailTable', '7.0.5');

COMMIT;

START TRANSACTION;

ALTER TABLE "Tbl_OnlineAftFail"
DROP COLUMN "ErrorMessage";

ALTER TABLE "Tbl_OnlineAftFail"
DROP COLUMN "PointAmount";

ALTER TABLE "Tbl_OnlineAftFail"
RENAME COLUMN "CreditAmount" TO "ErrorCode";

INSERT INTO
    "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES
    ('20230720094443_UpdateOnlineAftFail', '7.0.5');

COMMIT;

START TRANSACTION;

ALTER TABLE "Tbl_UserLoginRecord"
ALTER COLUMN "UpdatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_UserLoginRecord"
ALTER COLUMN "CreatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_UnselectedEgmTransaction"
ALTER COLUMN "UpdatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_UnselectedEgmTransaction"
ALTER COLUMN "CreatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_SmsVerify"
ALTER COLUMN "UpdatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_SmsVerify"
ALTER COLUMN "CreatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_SmsMaster"
ALTER COLUMN "UpdatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_SmsMaster"
ALTER COLUMN "CreatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_Photo"
ALTER COLUMN "UpdatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_Photo"
ALTER COLUMN "CreatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_PaymentMethodCurrency"
ALTER COLUMN "UpdatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_PaymentMethodCurrency"
ALTER COLUMN "CreatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_PaymentMethod"
ALTER COLUMN "UpdatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_PaymentMethod"
ALTER COLUMN "CreatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_OnlineWallet"
ALTER COLUMN "UpdatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_OnlineWallet"
ALTER COLUMN "CreatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_OnlineUserTransaction"
ALTER COLUMN "UpdatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_OnlineUserTransaction"
ALTER COLUMN "CreatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_OnlineUserInvitation"
ALTER COLUMN "UpdatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_OnlineUserInvitation"
ALTER COLUMN "CreatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_OnlineUser"
ALTER COLUMN "UpdatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_OnlineUser"
ALTER COLUMN "CreatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_OnlineAftFail"
ALTER COLUMN "UpdatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_OnlineAftFail"
ALTER COLUMN "CreatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_Invitation"
ALTER COLUMN "UpdatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_Invitation"
ALTER COLUMN "CreatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_InternalUser"
ALTER COLUMN "UpdatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_InternalUser"
ALTER COLUMN "CreatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_EgmTransaction"
ALTER COLUMN "UpdatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_EgmTransaction"
ALTER COLUMN "CreatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_EgmDisconnectionLog"
ALTER COLUMN "UpdatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_EgmDisconnectionLog"
ALTER COLUMN "CreatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_EgmAppUser"
ALTER COLUMN "UpdatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_EgmAppUser"
ALTER COLUMN "CreatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_Egm"
ALTER COLUMN "UpdatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_Egm"
ALTER COLUMN "CreatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_Customer"
ALTER COLUMN "UpdatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_Customer"
ALTER COLUMN "CreatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_CurrencyRate"
ALTER COLUMN "UpdatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_CurrencyRate"
ALTER COLUMN "CreatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_Currency"
ALTER COLUMN "UpdatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_Currency"
ALTER COLUMN "CreatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_BvacNotify"
ALTER COLUMN "UpdatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_BvacNotify"
ALTER COLUMN "CreatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_BvacMaster"
ALTER COLUMN "UpdatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_BvacMaster"
ALTER COLUMN "CreatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_AppUserRefreshToken"
ALTER COLUMN "UpdatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_AppUserRefreshToken"
ALTER COLUMN "CreatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_AftTransaction"
ALTER COLUMN "UpdatedAt" TYPE timestamp(3)
with
    time zone;

ALTER TABLE "Tbl_AftTransaction"
ALTER COLUMN "CreatedAt" TYPE timestamp(3)
with
    time zone;

INSERT INTO
    "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES
    (
        '20230731072541_ModifyBaseEntityTimestamp',
        '7.0.5'
    );

COMMIT;

START TRANSACTION;

ALTER TABLE "Tbl_UnselectedEgmTransaction"
DROP COLUMN "EgmCashCredit";

ALTER TABLE "Tbl_UnselectedEgmTransaction"
DROP COLUMN "EgmPromoCredit";

ALTER TABLE "Tbl_EgmTransaction"
DROP COLUMN "EgmCashCredit";

ALTER TABLE "Tbl_EgmTransaction"
DROP COLUMN "EgmPromoCredit";

INSERT INTO
    "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES
    (
        '20230807061947_RemoveBaseEgmTransactionColumn',
        '7.0.5'
    );

COMMIT;

START TRANSACTION;

ALTER TABLE "Tbl_Egm" ADD "AppUserId" text NULL;

ALTER TABLE "AspNetUsers" ADD "EgmId" integer NULL;

INSERT INTO
    "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES
    ('20230823095754_UpdateEgmAndAppUser', '7.0.5');

COMMIT;

START TRANSACTION;

CREATE INDEX "IX_Tbl_Egm_AppUserId" ON "Tbl_Egm" ("AppUserId");

ALTER TABLE "Tbl_Egm" ADD CONSTRAINT "FK_Tbl_Egm_AspNetUsers_AppUserId" FOREIGN KEY ("AppUserId") REFERENCES "AspNetUsers" ("Id");

INSERT INTO
    "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES
    ('20230823105124_UpdateEgm', '7.0.5');

COMMIT;

START TRANSACTION;

ALTER TABLE "Tbl_AppUserRefreshToken"
DROP CONSTRAINT "FK_Tbl_AppUserRefreshToken_AspNetUsers_AppUserId";

ALTER TABLE "Tbl_AppUserRefreshToken" ADD CONSTRAINT "FK_Tbl_AppUserRefreshToken_AspNetUsers_AppUserId" FOREIGN KEY ("AppUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE;

INSERT INTO
    "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES
    ('20230824063741_UpdateAppUserCascade', '7.0.5');

COMMIT;