version: "3.7" # Docker Engine release 18.02.0+

services:
  postgres:
    container_name: postgresql
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-db:/data/postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}


volumes:
  postgres-db:
    driver: local